Africa = [
    'Nigeria',
    'Ethiopia',
    'Egypt',
    'Democratic Republic of the Congo',
    'South Africa',
    'Tanzania',
    'Kenya',
    'Algeria',
    'Uganda',
    'Sudan',
    'Morocco',
    'Ghana',
    'Mozambique',
    'Ivory Coast',
    'Madagascar',
    'Angola',
    'Cameroon',
    'Niger',
    'Burkina Faso',
    'Mali',
    'Malawi',
    'Zambia',
    'Senegal',
    'Zimbabwe',
    'Chad',
    'Guinea',
    'Tunisia',
    'Rwanda',
    'South Sudan',
    'Benin',
    'Somalia',
    'Burundi',
    'Togo',
    'Libya',
    'Sierra Leone',
    'Central African Republic',
    'Eritrea',
    'Congo Brazzaville',
    'Liberia',
    'Mauritania',
    'Gabon',
    'Namibia',
    'Botswana',
    'Lesotho',
    'Equatorial Guinea',
    'Gambia',
    'Guinea-Bissau',
    'Mauritius',
    'Swaziland',
    'Djibouti',
    'Reunion',
    'Comoros',
    'Western Sahara',
    'Cape Verde',
    'Mayotte',
    'Sao Tome and Principe',
    'Seychelles',
    'Saint Helena',
]